DROP TABLE IF EXISTS articles;
CREATE TABLE articles ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(MAX) NOT NULL, url VARCHAR(MAX) NOT NULL, ts timestamp NOT NULL, user_id integer );
DROP TABLE IF EXISTS read_lists;
CREATE TABLE read_lists ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(MAX) NOT NULL, ts timestamp NOT NULL, user_id integer );
DROP TABLE IF EXISTS read_list_article_relations;
CREATE TABLE read_list_article_relations ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, read_list_id integer, article_id integer );